# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua_text', models.CharField(max_length=50)),
                ('ru_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('Question', 'Question'), ('Video', 'Video'), ('Starting', 'Starting'), ('Login', 'Login'), ('Lottery', 'Lottery'), ('FinalPage', 'FinalPage')], max_length=50)),
                ('ua_title', models.CharField(max_length=50)),
                ('ru_title', models.CharField(max_length=50)),
                ('ua_heading', models.TextField(blank=True, max_length=500)),
                ('ru_heading', models.TextField(blank=True, max_length=500)),
                ('ua_text', models.TextField(blank=True, max_length=2000)),
                ('ru_text', models.TextField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='0', max_length=10)),
                ('type', models.CharField(choices=[('SimpleOpenQuestion', 'SimpleOpenQuestion'), ('SimpleQuestionWithOneAnswer', 'SimpleQuestionWithOneAnswer'), ('SimpleQuestionWithSeveralAnswers', 'SimpleQuestionWithSeveralAnswers'), ('TableQuestion', 'TableQuestion'), ('QuestionWithOptionsAndUserAnswer', 'QuestionWithOptionsAndUserAnswer'), ('LanguageChoosing', 'LanguageChoosing'), ('DateTimeChoosing', 'DateTimeChoosing'), ('QuestionWithSeveralOptionsAndUserAnswer', 'QuestionWithSeveralOptionsAndUserAnswer'), ('TableHeadingQuestion', 'TableHeadingQuestion')], max_length=50)),
                ('ua_heading', models.CharField(max_length=200)),
                ('ru_heading', models.CharField(max_length=200)),
                ('ua_text', models.CharField(blank=True, max_length=500)),
                ('ru_text', models.CharField(blank=True, max_length=500)),
                ('pub_date', models.DateTimeField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('identity', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('UA', 'Ukrainian'), ('RU', 'Russian')], default='UA', max_length=20)),
                ('page', models.IntegerField(default=0)),
                ('spreadsheet_row', models.AutoField(primary_key=True, serialize=False)),
                ('lottery_number', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Questionnaire'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Question'),
        ),
        migrations.AddField(
            model_name='condition',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Option'),
        ),
        migrations.AddField(
            model_name='condition',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Page'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Respondent'),
        ),
    ]
