# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(default=0)),
                ('page_type', models.CharField(choices=[('Question', 'Question'), ('Video', 'Video'), ('Starting', 'Starting')], max_length=50)),
                ('page_title', models.CharField(max_length=50)),
                ('page_heading', models.CharField(blank=True, max_length=200)),
                ('page_text', models.CharField(blank=True, max_length=2000)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=0)),
                ('question_type', models.CharField(choices=[('SimpleOpenQuestion', 'SimpleOpenQuestion'), ('SimpleQuestionWithOneAnswer', 'SimpleQuestionWithOneAnswer'), ('SimpleQuestionWithSeveralAnswers', 'SimpleQuestionWithSeveralAnswers'), ('TableQuestion', 'TableQuestion')], max_length=50)),
                ('question_heading', models.CharField(max_length=200)),
                ('question_text', models.CharField(blank=True, max_length=500)),
                ('pub_date', models.DateTimeField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_name', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=50)),
                ('page', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Questionnaire'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Respondent'),
        ),
    ]
