# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20170130_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='respondent',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Respondent',
        ),
    ]
