# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20170130_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_entered', models.BooleanField(default=False)),
                ('page_on', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='page',
        ),
        migrations.AddField(
            model_name='respondent',
            name='activity',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='poll.RespondentActivity'),
            preserve_default=False,
        ),
    ]
