# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20170130_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='id',
        ),
        migrations.AddField(
            model_name='respondent',
            name='page',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='identity',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='RespondentActivity',
        ),
    ]
