# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20170130_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='prepared',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SimpleOpenQuestion', 'SimpleOpenQuestion'), ('SimpleQuestionWithOneAnswer', 'SimpleQuestionWithOneAnswer'), ('SimpleQuestionWithSeveralAnswers', 'SimpleQuestionWithSeveralAnswers'), ('TableQuestion', 'TableQuestion'), ('QuestionWithOptionsAndUserAnswer', 'QuestionWithOptionsAndUserAnswer')], max_length=50),
        ),
    ]
