# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20170130_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='prepared',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='poll.Question'),
            preserve_default=False,
        ),
    ]
