# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_condition_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
